include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - 'lib/generated/**'
    - 'packages/**'
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    always_declare_return_types: warning
    camel_case_types: warning
    empty_constructor_bodies: warning
    annotate_overrides: warning
    avoid_init_to_null: warning
    constant_identifier_names: warning
    slash_for_doc_comments: warning
    type_annotate_public_apis: warning
    type_init_formals: warning
    sort_unnamed_constructors_first: warning
    unnecessary_brace_in_string_interps: warning
    no_duplicate_case_values: warning
    prefer_void_to_null: warning
    lines_longer_than_80_chars: ignore
    always_put_control_body_on_new_line: warning
    unnecessary_await_in_return: warning
    use_to_and_as_if_applicable: warning
    valid_regexps: warning
    throw_in_finally: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    return_of_invalid_type: warning
    missing_default_value_for_parameter: warning
    not_initialized_non_nullable_instance_field: warning
    unchecked_use_of_nullable_value: warning
    argument_type_not_assignable: warning
    not_assigned_potentially_non_nullable_local_variable: warning
    invalid_assignment: warning
    not_initialized_non_nullable_variable: warning
    return_of_invalid_type_from_closure: warning
    list_element_type_not_assignable: warning
    field_initializer_not_assignable: warning
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_classes_with_only_static_members
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_returning_this
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - comment_references
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - only_throw_errors
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
